/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robo;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Orion
 */
public class RoboBody extends javax.swing.JFrame {
    Robo bobby = new Robo("Bobby", "20/20/2020", 10.0);
    /**
     * Creates new form RoboBody
     */
    public RoboBody() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roboPanel = new javax.swing.JPanel();
        subtrairButton = new javax.swing.JButton();
        somaButton = new javax.swing.JButton();
        multiplicaButton = new javax.swing.JButton();
        divisaoButton = new javax.swing.JButton();
        roboLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 520));
        setResizable(false);

        roboPanel.setMaximumSize(new java.awt.Dimension(504, 504));
        roboPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        roboPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        subtrairButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        subtrairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/menosButton.jpg"))); // NOI18N
        subtrairButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subtrairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtrairButtonMouseClicked(evt);
            }
        });

        somaButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        somaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/maisButton.jpg"))); // NOI18N
        somaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        somaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                somaButtonMouseClicked(evt);
            }
        });

        multiplicaButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        multiplicaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/vezesButton.jpg"))); // NOI18N
        multiplicaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplicaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicaButtonMouseClicked(evt);
            }
        });

        divisaoButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        divisaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/dividirButton.jpg"))); // NOI18N
        divisaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divisaoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisaoButtonMouseClicked(evt);
            }
        });

        roboLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/RoboBody.png"))); // NOI18N

        javax.swing.GroupLayout roboPanelLayout = new javax.swing.GroupLayout(roboPanel);
        roboPanel.setLayout(roboPanelLayout);
        roboPanelLayout.setHorizontalGroup(
            roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roboPanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(roboPanelLayout.createSequentialGroup()
                        .addComponent(somaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtrairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roboPanelLayout.createSequentialGroup()
                        .addComponent(multiplicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roboPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roboLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        roboPanelLayout.setVerticalGroup(
            roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roboPanelLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(somaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtrairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiplicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roboPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roboLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 489, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roboPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roboPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void somaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_somaButtonMouseClicked
        try{
            //JOptionPane.showMessageDialog(null, "O resultado é "+String.valueOf(bobby.operacional("+"))+"!", "Resultado", JOptionPane.INFORMATION_MESSAGE, bobby.roboIcon);
            bobby.operacional("+");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_somaButtonMouseClicked

    private void subtrairButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtrairButtonMouseClicked
        try{
            bobby.operacional("-");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_subtrairButtonMouseClicked

    private void multiplicaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicaButtonMouseClicked
        try{
            bobby.operacional("*");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_multiplicaButtonMouseClicked

    private void divisaoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisaoButtonMouseClicked
        try{
            bobby.operacional("/");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_divisaoButtonMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoboBody().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divisaoButton;
    private javax.swing.JButton multiplicaButton;
    private javax.swing.JLabel roboLabel;
    private javax.swing.JPanel roboPanel;
    private javax.swing.JButton somaButton;
    private javax.swing.JButton subtrairButton;
    // End of variables declaration//GEN-END:variables
}
