/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robo;

/**
 *
 * @author Orion
 */
public class RoboBody extends javax.swing.JFrame {

    /**
     * Creates new form RoboBody
     */
    public RoboBody() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roboPanel = new javax.swing.JPanel();
        subtrairButton = new javax.swing.JButton();
        somaButton = new javax.swing.JButton();
        multiplicaButton = new javax.swing.JButton();
        divisaoButton = new javax.swing.JButton();
        roboLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 520));
        setResizable(false);

        roboPanel.setMaximumSize(new java.awt.Dimension(500, 500));
        roboPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        roboPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        subtrairButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        subtrairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/menosButton.jpg"))); // NOI18N

        somaButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        somaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/maisButton.jpg"))); // NOI18N

        multiplicaButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        multiplicaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/vezesButton.jpg"))); // NOI18N

        divisaoButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        divisaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/dividirButton.jpg"))); // NOI18N

        roboLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo/RoboBody.png"))); // NOI18N

        javax.swing.GroupLayout roboPanelLayout = new javax.swing.GroupLayout(roboPanel);
        roboPanel.setLayout(roboPanelLayout);
        roboPanelLayout.setHorizontalGroup(
            roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roboPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roboPanelLayout.createSequentialGroup()
                        .addComponent(somaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtrairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roboPanelLayout.createSequentialGroup()
                        .addComponent(multiplicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roboPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roboLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)))
        );
        roboPanelLayout.setVerticalGroup(
            roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roboPanelLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(somaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtrairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiplicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(203, 203, 203))
            .addGroup(roboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roboPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roboLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roboPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roboPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoboBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoboBody().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divisaoButton;
    private javax.swing.JButton multiplicaButton;
    private javax.swing.JLabel roboLabel;
    private javax.swing.JPanel roboPanel;
    private javax.swing.JButton somaButton;
    private javax.swing.JButton subtrairButton;
    // End of variables declaration//GEN-END:variables
}
